import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/shared/Navbar/Navbar";
import TopBar from "@/components/shared/Navbar/TopBar";
import { roboto_serif } from "@/utils/Font/font";
import Footer from "@/components/shared/Footer/Footer";

// const roboto = Sora({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AntdRegistry>
      <html lang="en" className={roboto_serif.className}>
        <body>
          <TopBar />
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </body>
      </html>
    </AntdRegistry>
  );
}
