import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/shared/Navbar/Navbar";
import TopBar from "@/components/shared/Navbar/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AntdRegistry>
      <html lang="en">
        <body>
          <TopBar />
          <Navbar />
          <div className="min-h-screen">{children}</div>
        </body>
      </html>
    </AntdRegistry>
  );
}
